name: Snapshot Binaries

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  GO_VERSION: "1.24.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanitize branch name
        if: github.event_name == 'pull_request'
        id: sanitize
        uses: ./.github/actions/sanitize-branch-name
        with:
          branch-name: ${{ github.head_ref }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Package Binaries
        id: package
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            SAFE_BRANCH="${{ steps.sanitize.outputs.sanitized-name }}"
            VERSION="pr-${SAFE_BRANCH}-${GITHUB_SHA::7}"
            echo "artifact_name=flotilla-snapshot-pr-${SAFE_BRANCH}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          else
            VERSION="sha-${GITHUB_SHA::7}"
            echo "artifact_name=flotilla-snapshot-sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi
          VERSION="${VERSION}" make package-binaries

      - name: Upload Snapshot Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.artifact_name }}
          path: dist/release/**
